/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pzbsbcapgwbfkbmhaszb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6YnNiY2FwZ3diZmtibWhhc3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MzMxMDIsImV4cCI6MjA3OTMwOTEwMn0.1F4EV8f3gHvGlEeBRWkQXNUu-92bStJ3G-HSkHA_TUg"